spring:
  config:
    import: optional:file:/home/ec2-user/globeot-back/.env.properties
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    region: ${S3_REGION}
